package ecommerce

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetEcommerceStoresParams creates a new GetEcommerceStoresParams object
// with the default values initialized.
func NewGetEcommerceStoresParams() *GetEcommerceStoresParams {
	var ()
	return &GetEcommerceStoresParams{}
}

/*GetEcommerceStoresParams contains all the parameters to send to the API endpoint
for the get ecommerce stores operation typically these are written to a http.Request
*/
type GetEcommerceStoresParams struct {

	/*ExcludedFields
	  A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.

	*/
	ExcludedFields []string
	/*Fields
	  A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.

	*/
	Fields []string
}

// WithExcludedFields adds the excludedFields to the get ecommerce stores params
func (o *GetEcommerceStoresParams) WithExcludedFields(excludedFields []string) *GetEcommerceStoresParams {
	o.ExcludedFields = excludedFields
	return o
}

// WithFields adds the fields to the get ecommerce stores params
func (o *GetEcommerceStoresParams) WithFields(fields []string) *GetEcommerceStoresParams {
	o.Fields = fields
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetEcommerceStoresParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	valuesExcludedFields := o.ExcludedFields

	joinedExcludedFields := swag.JoinByFormat(valuesExcludedFields, "")
	// query array param excluded_fields
	if err := r.SetQueryParam("excluded_fields", joinedExcludedFields...); err != nil {
		return err
	}

	valuesFields := o.Fields

	joinedFields := swag.JoinByFormat(valuesFields, "")
	// query array param fields
	if err := r.SetQueryParam("fields", joinedFields...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
