package carts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// New creates a new carts API client.
func New(transport client.Transport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for carts API
*/
type Client struct {
	transport client.Transport
	formats   strfmt.Registry
}

/*
GetEcommerceStoreStoreIDCarts words words

words words
*/
func (a *Client) GetEcommerceStoreStoreIDCarts(params *GetEcommerceStoreStoreIDCartsParams) (*GetEcommerceStoreStoreIDCartsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetEcommerceStoreStoreIDCartsParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetEcommerceStoreStoreIDCarts",
		Method:             "GET",
		PathPattern:        "/ecommerce/store/{store_id}/carts",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetEcommerceStoreStoreIDCartsReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetEcommerceStoreStoreIDCartsOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport client.Transport) {
	a.transport = transport
}
