package carts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetEcommerceStoreStoreIDCartsReader is a Reader for the GetEcommerceStoreStoreIDCarts structure.
type GetEcommerceStoreStoreIDCartsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetEcommerceStoreStoreIDCartsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetEcommerceStoreStoreIDCartsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEcommerceStoreStoreIDCartsOK creates a GetEcommerceStoreStoreIDCartsOK with default headers values
func NewGetEcommerceStoreStoreIDCartsOK() *GetEcommerceStoreStoreIDCartsOK {
	return &GetEcommerceStoreStoreIDCartsOK{}
}

/*GetEcommerceStoreStoreIDCartsOK handles this case with default header values.

OK
*/
type GetEcommerceStoreStoreIDCartsOK struct {
}

func (o *GetEcommerceStoreStoreIDCartsOK) Error() string {
	return fmt.Sprintf("[GET /ecommerce/store/{store_id}/carts][%d] getEcommerceStoreStoreIdCartsOK ", 200)
}

func (o *GetEcommerceStoreStoreIDCartsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
