package store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/mattbaird/gochimp/swagger/models"
)

// GetEcommerceStoresReader is a Reader for the GetEcommerceStores structure.
type GetEcommerceStoresReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetEcommerceStoresReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetEcommerceStoresOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetEcommerceStoresDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetEcommerceStoresOK creates a GetEcommerceStoresOK with default headers values
func NewGetEcommerceStoresOK() *GetEcommerceStoresOK {
	return &GetEcommerceStoresOK{}
}

/*GetEcommerceStoresOK handles this case with default header values.

Success
*/
type GetEcommerceStoresOK struct {
	Payload bool
}

func (o *GetEcommerceStoresOK) Error() string {
	return fmt.Sprintf("[GET /ecommerce/stores][%d] getEcommerceStoresOK  %+v", 200, o.Payload)
}

func (o *GetEcommerceStoresOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEcommerceStoresDefault creates a GetEcommerceStoresDefault with default headers values
func NewGetEcommerceStoresDefault(code int) *GetEcommerceStoresDefault {
	return &GetEcommerceStoresDefault{
		_statusCode: code,
	}
}

/*GetEcommerceStoresDefault handles this case with default header values.

Error
*/
type GetEcommerceStoresDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get ecommerce stores default response
func (o *GetEcommerceStoresDefault) Code() int {
	return o._statusCode
}

func (o *GetEcommerceStoresDefault) Error() string {
	return fmt.Sprintf("[GET /ecommerce/stores][%d] GetEcommerceStores default  %+v", o._statusCode, o.Payload)
}

func (o *GetEcommerceStoresDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
