package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// APIResponse is the response to an API call.
type APIResponse struct {

	/* User ID
	 */
	AccountID *string `json:"account_id,omitempty"`

	/* Login Name
	 */
	AccountName *string `json:"account_name,omitempty"`

	/* contact
	 */
	Contact *APIResponseContact `json:"contact,omitempty"`

	/* Account Email
	 */
	Email *string `json:"email,omitempty"`

	/* industry stats
	 */
	IndustryStats *APIResponseIndustryStats `json:"industry_stats,omitempty"`

	/* Last Login
	 */
	LastLogin *string `json:"last_login,omitempty"`

	/* links
	 */
	Links Links `json:"links,omitempty"`

	/* MailChimp Pro
	 */
	ProEnabled *bool `json:"pro_enabled,omitempty"`

	/* Role
	 */
	Role *string `json:"role,omitempty"`

	/* Total Subscribers
	 */
	TotalSubscribers *int64 `json:"total_subscribers,omitempty"`
}

// Validate validates this api response
func (m *APIResponse) Validate(formats strfmt.Registry) error {
	return nil
}

/*APIResponseContact API response contact

swagger:model APIResponseContact
*/
type APIResponseContact struct {

	/* Address Line 1
	 */
	Addr1 *string `json:"addr1,omitempty"`

	/* Address Line 2
	 */
	Addr2 *string `json:"addr2,omitempty"`

	/* City
	 */
	City *string `json:"city,omitempty"`

	/* Company
	 */
	Company *string `json:"company,omitempty"`

	/* Country
	 */
	Country *string `json:"country,omitempty"`

	/* State
	 */
	State *string `json:"state,omitempty"`

	/* Zipcode
	 */
	Zip *string `json:"zip,omitempty"`
}

// Validate validates this API response contact
func (m *APIResponseContact) Validate(formats strfmt.Registry) error {
	return nil
}

/*APIResponseIndustryStats API response industry stats

swagger:model APIResponseIndustryStats
*/
type APIResponseIndustryStats struct {

	/* Bounce Rate
	 */
	BounceRate *int64 `json:"bounce_rate,omitempty"`

	/* Click Rate
	 */
	ClickRate *int64 `json:"click_rate,omitempty"`

	/* Open Rate
	 */
	OpenRate *int64 `json:"open_rate,omitempty"`
}

// Validate validates this API response industry stats
func (m *APIResponseIndustryStats) Validate(formats strfmt.Registry) error {
	return nil
}
