package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Error error

swagger:model Error
*/
type Error struct {

	/* Error Message
	 */
	Detail *string `json:"detail,omitempty"`

	/* Instance ID
	 */
	Instance *string `json:"instance,omitempty"`

	/* HTTP Status Code
	 */
	Status *int64 `json:"status,omitempty"`

	/* Error Title
	 */
	Title *string `json:"title,omitempty"`

	/* Problem Type
	 */
	Type *string `json:"type,omitempty"`
}

// Validate validates this error
func (m *Error) Validate(formats strfmt.Registry) error {
	return nil
}
