package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Link link

swagger:model Link
*/
type Link struct {

	/* Href
	 */
	Href *string `json:"href,omitempty"`

	/* Method
	 */
	Method *string `json:"method,omitempty"`

	/* Rel
	 */
	Rel *string `json:"rel,omitempty"`

	/* Schema
	 */
	Schema *string `json:"schema,omitempty"`

	/* Target Schema
	 */
	TargetSchema *string `json:"targetSchema,omitempty"`
}

// Validate validates this link
func (m *Link) Validate(formats strfmt.Registry) error {
	return nil
}
