package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// New creates a new operations API client.
func New(transport client.Transport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport client.Transport
	formats   strfmt.Registry
}

/*
PostEcommerceStores adds store

Add a new store to your account
*/
func (a *Client) PostEcommerceStores(params *PostEcommerceStoresParams) (*PostEcommerceStoresOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostEcommerceStoresParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "PostEcommerceStores",
		Method:             "POST",
		PathPattern:        "/ecommerce/stores",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostEcommerceStoresReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostEcommerceStoresOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport client.Transport) {
	a.transport = transport
}
