package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewPostEcommerceStoresParams creates a new PostEcommerceStoresParams object
// with the default values initialized.
func NewPostEcommerceStoresParams() *PostEcommerceStoresParams {
	var ()
	return &PostEcommerceStoresParams{}
}

/*PostEcommerceStoresParams contains all the parameters to send to the API endpoint
for the post ecommerce stores operation typically these are written to a http.Request
*/
type PostEcommerceStoresParams struct {

	/*Body*/
	Body PostEcommerceStoresBody
}

// WithBody adds the body to the post ecommerce stores params
func (o *PostEcommerceStoresParams) WithBody(body PostEcommerceStoresBody) *PostEcommerceStoresParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostEcommerceStoresParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
